#!/usr/bin/env bash
# install nginx and adjust default homepage
apt-get -y update
apt-get -y install nginx
sed -i '21s/^.*listen 80;/    listen 80;/' /etc/nginx/sites-enabled/default
ufw allow 'Nginx HTTP'
echo Hello World > /var/www/html/index.nginx-debian.html
service nginx start
