#!/usr/bin/env bash
# install nginx and adjust default homepage
# add redirection
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo Hello World! > /var/www/html/index.nginx-debian.html
sed -i "/^\s*server_name\s.*;/a\    rewrite ^/redirect_me https://twitter.com/Jbusmoove permanent;" /etc/nginx/sites-available/default
service nginx start
