#!/usr/bin/env bash
# Install and configure HAProxy load balancer to 195722-lb-01
# sends traffic to web-01 and web-02.


CONFGF="\\\nlisten appname 0.0.0.0:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 195722-web-01 18.234.169.88 check\n\tserver 195722-web-02 100.26.253.133 check\n"

sudo apt-get update
sudo apt-get -y install nginx
#version 1.5 and above
sudo apt-get install -y haproxy=2.5\*
#enable HAproxy can be managed via an init script
sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
# include roundrobin and two servers
sudo sed -i "\$a $CONFGF" /etc/haproxy/haproxy.cfg

# Configure HAProxy
cat << EOF | sudo tee /etc/haproxy/haproxy.cfg
frontend app_frontend
    bind 0.0.0.0:80
    mode http
    default_backend app_servers

backend app_servers
    balance roundrobin
    mode http
    server 195722-web-01 18.234.169.88:80 check
    server 195722-web-02 100.26.253.133:80 check
EOF
sudo service haproxy start
