#!/usr/bin/env bash
#makes nginx installation to listen on port 80
apt-get update
apt-get install -y curl nginx
rm /etc/nginx/sites-available/*~
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
