#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic
#+ except for TCP ports 22, 443, and 80.

# Update the package list
apt-get update

# Install UFW
apt-get install ufw

# Enable IPv6 support in UFW (if needed)
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw

# Enable and configure UFW
ufw disable       # Disable UFW to make changes
ufw default deny incoming   # Set the default incoming policy to deny
ufw default allow outgoing  # Set the default outgoing policy to allow
ufw allow 22/tcp   # Allow SSH (port 22)
ufw allow 443/tcp  # Allow HTTPS (port 443)
ufw allow 80/tcp   # Allow HTTP (port 80)

# Enable UFW.
ufw enable
